In [1]:
import numpy as np


In [2]:
#current state - initial state
i=np.matrix([[0.7,0.3]])

In [3]:
#transition probabilities
t=np.matrix([[0.4,0.6],[0.2,0.8]])


In [4]:
#1st camp.
t1=i*t

In [6]:
#2nd camp.
t2=t1*t

In [7]:
#after 3rd camp.
t3=t2*t

In [8]:
#after 4th
t4=t3*t

In [9]:
print(t1)

[[0.34 0.66]]


In [10]:
print(t2)

[[0.268 0.732]]


In [11]:
print(t3)

[[0.2536 0.7464]]


In [12]:
print(t4)

[[0.25072 0.74928]]


In [14]:
t5=t4*t

t5

In [15]:
t5

matrix([[0.250144, 0.749856]])

In [16]:
t6=t5*t


In [17]:
t6

matrix([[0.2500288, 0.7499712]])

In [18]:
t7=t6*t

In [19]:
t7

matrix([[0.25000576, 0.74999424]])

In [20]:
t8=t7*t

In [21]:
t8

matrix([[0.25000115, 0.74999885]])

In [22]:
t9=t8*t

In [24]:
t9

matrix([[0.25000023, 0.74999977]])

In [25]:
t10=t9*t

In [26]:
t10


matrix([[0.25000005, 0.74999995]])

In [27]:
t11=t10*t

In [28]:
t11

matrix([[0.25000001, 0.74999999]])

In [29]:
t12=t11*t

In [30]:
t12

matrix([[0.25, 0.75]])

In [32]:
t13=t12*t

In [33]:
t13

matrix([[0.25, 0.75]])

In [34]:
print(t13*t)

[[0.25 0.75]]
